import { NextRequest, NextResponse } from 'next/server';
import { getServiceClient } from '@/lib/supabase';
import { checkNumberExists, normalizePhone } from '@/lib/waha';

type RegisterBody = {
  name?: string;
  phone?: string;
  company?: string;
  occupation?: string;
};

/**
 * POST /api/register
 * 1. Validate + normalize the form payload.
 * 2. Live-check the number on WhatsApp via WAHA
 *    GET /api/contacts/check-exists?phone=…&session=…
 * 3. Insert into Supabase `visitors` (qr_token auto-generated).
 * 4. Return { qr_token, name }.
 */
export async function POST(req: NextRequest) {
  let body: RegisterBody;
  try {
    body = (await req.json()) as RegisterBody;
  } catch {
    return NextResponse.json({ error: 'Invalid JSON body' }, { status: 400 });
  }

  const name = (body.name ?? '').trim();
  const phone = normalizePhone(body.phone ?? '');
  const company = (body.company ?? '').trim() || null;
  const occupation = (body.occupation ?? '').trim() || null;

  if (!name) {
    return NextResponse.json({ error: 'Name is required' }, { status: 400 });
  }
  if (!/^\d{8,15}$/.test(phone)) {
    return NextResponse.json(
      { error: 'Enter a valid phone number with country code (digits only)' },
      { status: 400 }
    );
  }

  // Live WhatsApp verification.
  try {
    const { numberExists } = await checkNumberExists(phone);
    if (!numberExists) {
      return NextResponse.json(
        { error: 'Not a valid WhatsApp number' },
        { status: 400 }
      );
    }
  } catch (e) {
    const msg = e instanceof Error ? e.message : 'Unknown error';
    console.error('WAHA verification error:', msg);
    return NextResponse.json(
      { error: 'Could not verify WhatsApp number right now. Please try again.' },
      { status: 502 }
    );
  }

  // Save the visitor; qr_token is generated by the DB default.
  try {
    const supabase = getServiceClient();
    const { data, error } = await supabase
      .from('visitors')
      .insert({ name, phone, company, occupation })
      .select('id, qr_token, name')
      .single();

    if (error) {
      // 23505 = unique violation (duplicate phone)
      if (error.code === '23505') {
        return NextResponse.json(
          { error: 'This phone number is already registered' },
          { status: 409 }
        );
      }
      throw error;
    }

    return NextResponse.json(
      { qr_token: data.qr_token, name: data.name },
      { status: 201 }
    );
  } catch (e) {
    const msg = e instanceof Error ? e.message : 'Unknown error';
    console.error('Supabase insert error:', msg);
    return NextResponse.json(
      { error: 'Registration failed. Please try again.' },
      { status: 500 }
    );
  }
}
